### ISSUE TITLE
about 3D molecular conformation code

### ISSUE THREAD

**Issue by klez1** [andreimano/MolMix#1]
Hello, I am very interested in your work. If I only need the code for the 3D molecular conformation as an encoder for my own work, can I do that? Could you tell me specifically where this part of the code is? Thank you!

**Comment by andreimano** [comment]
Hi @llloopy - what exactly do you require?

The conformers for the MARCEL experiments are already available in the dataset. The ones for MoleculeNet are generated with RDKit.

Is your question regarding the data or model?

**Comment by andreimano** [comment]
Since this issue has been inactive for a few weeks, I will close it. Please let me know if you have further issues.
